# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.**']

name: render-rmarkdown

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      THIS_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install ragg
        run: Rscript -e 'install.packages("ragg")'
      - name: Install remotes
        run: Rscript -e 'install.packages("remotes")'
      - name: Install markdown
        run: Rscript -e 'install.packages("markdown")'
      - name: Install xml2
        run: Rscript -e 'install.packages("xml2")'
      - name: Install sf
        run: Rscript -e 'install.packages("sf", type = "mac.binary")'
      - name: Install self
        run: Rscript -e 'remotes::install_github(Sys.getenv("THIS_REPO"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git add README.md man/figures/README-*
          git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
